### ISSUE TITLE
env file naming

### ISSUE THREAD

**Issue by coquer** [ageras-com/sherlock#9]
The naming for the env file could be confusing.

**Comment by shooka** [comment]
What exactly is confusing?

`.env` is the standard file name and the `vlucas/phpdotenv` package is widely used.

**Comment by coquer** [comment]
Because the current names do not tell me what kind of API is using; this names too general, **company_serice** implies that we are only using one service for all countries.

```
COMPANY_SERVICE_CVR_USERNAME=
COMPANY_SERVICE_CVR_PASSWORD=
```

A better name could be:

```
DISTRIBUTION_VIRK_USERNAME=
DISTRIBUTION_VIRK_PASSWORD=
```

**Comment by phidah** [comment]
How about

```
COMPANY_SERVICE_VIRK_USERNAME
COMPANY_SERVICE_VIRK_PASSWORD
```

Asides from that I'm no fan of ENV files as project configuration.

**Comment by coquer** [comment]
Will be release is next version
